name: BuyLotto645 weekly
on:
  #schedule:
  #  - cron: 0 0 * * 0 # every Sunday on 09:00 AM (KST)
  workflow_dispatch:      # 테스트를 위해 workflow가 dispatch 되는 경우 실행이 가능하도록 추가
jobs:
  BuyLotto645:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3    
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' 
      - name: Install dhapi
        run: |
          pip install dhapi packaging
      - name: Buy Lotto645
        run: |
          mkdir -p ~/.dhapi
          # secret에 저장된 내용을 프로필 파일에 저장 (TOML 형식이므로 값을 따옴표로 감싸야 함)
          printf '[default]\nusername = "%s"\npassword = "%s"\n' "$USERNAME" "$PASSWORD" > ~/.dhapi/credentials
          dhapi buy-lotto645 -y
        env:
            USERNAME: ${{ secrets.USER_ID }} # secret에 저장된 내용을 불러옴
            PASSWORD: ${{ secrets.USER_PW }}
